Ketan local branch
hmrc/reauth-performance-tests pull request #1
Opened 2024-07-15 15:27 UTC by ketanhirpara1

2024-07-23 11:48 UTC, chloe-c8 requested changes

2024-07-23 11:48 UTC, chloe-c8 commented on src/test/resources/logback.xml
> +    <logger name="io.gatling.http.engine.response" level="TRACE" />
comment this out, we dont want trace logs showing in staging

2024-07-23 11:48 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/requests/ReAuthRequest.scala
> +//  def postInitialise(action: String): HttpRequestBuilder = http("Create account in IDP store")
Can this be deleted? doesnt look like we are using it

2024-07-23 11:48 UTC, chloe-c8 commented on build.sbt
> +    "uk.gov.hmrc" %% "performance-test-runner" % "5.6.0" % "test",
I would remove this - we have the performance-test-runner already defined in our Dependencies.scala  file and this is overiding that version

2024-07-23 11:48 UTC, chloe-c8 commented on ra-smoke-test-local.sh
> +sm2 --stop OLJ_ALL IDENTITY_PROVIDER_ACCOUNT_CONTEXT
I think we need the CENTRALISED_AUTHORISATION_ALL profile. OLJ_ALL doesnt provide all the services we need

2024-07-23 11:48 UTC, chloe-c8 commented on src/test/resources/journeys.conf
> +#     http://www.apache.org/licenses/LICENSE-2.0
Where did all of these licenses come from? lol

2024-07-23 11:48 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/BasicSimulation.scala
> +//  setup("home-page", "Home Page") withRequests navigateToHomePage
remove - these are the template requests that are not needed for our service

2024-07-23 11:48 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/ReAuthParts.scala
> +//    postInitialise("AUTHN"),
remove rather than comment out

2024-07-23 11:48 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/ReAuthParts.scala
> +    postSubmitJourney,
dont need the comma at the end of this

2024-07-23 11:48 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/common/RequestFunctions.scala
> +
Do we use all of these functions?

2024-07-24 19:18 UTC, ketanhirpara1 commented on src/test/resources/journeys.conf
> +#     http://www.apache.org/licenses/LICENSE-2.0
Comment added automatically when IntelliJ reformats the code via auto reformat.

2024-07-25 10:30 UTC, chloe-c8 requested changes

2024-07-25 10:30 UTC, chloe-c8 commented on project/Dependencies.scala
you can delete this file

2024-07-25 10:30 UTC, chloe-c8 commented on src/test/resources/application.conf
> +# Licensed under the Apache License, Version 2.0 (the "License");
you can remove all of these apache licenses

2024-07-25 10:30 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/common/AppConfig.scala
> + */
doesnt seem like this file does anything - so I would remove it

2024-07-25 10:30 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/requests/BaseRequests.scala
> +package uk.gov.hmrc.perftests.reAuthJourney.requests
same here - nothing is in this file so I would remove

2024-07-25 10:30 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/requests/ReAuthRequest.scala
> +  def getOlfjJourneyId: HttpRequestBuilder = http("Req:6 START OLFJ JOURNEY ID")
I would name this something like "getOlgStartUrl" rather than journey Id, as the current name doesnt really show us whats going on - also change the http('') comment as well

2024-07-25 10:30 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/requests/ReAuthRequest.scala
> +  def getAuthorizeResponseOlfjJourneyId: HttpRequestBuilder = http("Req:7 AUTHORIZE RESPONSE")
typo in function name - its olg rather than olfj

also same as above, I wouldnt include "journeyId" in the function name. Only because it makes this function look like its grabbing a journeyId when its not

2024-07-25 10:30 UTC, chloe-c8 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/requests/ReAuthRequest.scala
> +  def getAuthorizeResponseOlfjJourneyId2: HttpRequestBuilder = http("Req:9 AUTHORIZE RESPONSE FOR RE-SUBMIT JOURNEY")
Same as above comment, typo in function name and dont use journeyId in the name

2024-07-25 10:42 UTC, ketanhirpara1 commented on src/test/resources/application.conf
> +# Licensed under the Apache License, Version 2.0 (the "License");
Not sure why it came up again. I did make sure to remove all of them before pushing my changes, but it comes up again. I will find out how to disable auto comment in IntelliJ.

2024-07-25 10:57 UTC, ketanhirpara1 commented on src/test/scala/uk/gov/hmrc/perftests/reAuthJourney/requests/BaseRequests.scala
> +package uk.gov.hmrc.perftests.reAuthJourney.requests
I have used 2 definitions from the ServiceConfiguration class in ReAuthRequest, and BaseRequests.scala extends the ServiceConfiguration class.

2024-07-26 11:16 UTC, merged